# Generated by Django 4.0 on 2022-01-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.CharField(default='2021-01', max_length=20)),
                ('demand', models.IntegerField()),
            ],
            options={
                'db_table': 'cheese',
            },
        ),
        migrations.CreateModel(
            name='chocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.CharField(default='2021-01', max_length=20)),
                ('demand', models.IntegerField()),
            ],
            options={
                'db_table': 'chocolate',
            },
        ),
        migrations.CreateModel(
            name='cream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.CharField(default='2021-01', max_length=20)),
                ('demand', models.IntegerField()),
            ],
            options={
                'db_table': 'cream',
            },
        ),
        migrations.CreateModel(
            name='meatfloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.CharField(default='2021-01', max_length=20)),
                ('demand', models.IntegerField()),
            ],
            options={
                'db_table': 'meatfloss',
            },
        ),
        migrations.CreateModel(
            name='redbean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.CharField(default='2021-01', max_length=20)),
                ('demand', models.IntegerField()),
            ],
            options={
                'db_table': 'redbean',
            },
        ),
    ]
